---
- name: Check K3s roles
  ansible.builtin.debug:
    msg: "{{ ansible_host }}: {{ k3s_role }}"

- name: Worker node tasks
  when: k3s_role == 'agent'
  block:
    - name: Gracefully stop worker
      ansible.builtin.command: /usr/local/bin/k3s-killall.sh
      changed_when: true
    - name: Uninstall K3s from worker
      ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
      changed_when: true

- name: Server node tasks
  when: k3s_role != 'agent'
  block:
    - name: Gracefully stop server
      ansible.builtin.command: /usr/local/bin/k3s-killall.sh
      changed_when: true
    - name: Uninstall K3s from server
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      changed_when: true
