---
# - name: Set hostname
#   hostname:
#     name: "{{ inventory_hostname }}"
- name: Get facts
  debug:
    msg: "{{ ansible_facts }}"

- name: Set master fact
  set_fact:
    k3s_role: "{{ (inventory_hostname == 'picluster-01' ) | ternary('master', 'worker') }}"