---
- name: Raspi Config setup
  import_tasks: raspi-config.yml

- name: Replace rsyslog logrotate Config
  copy:
    src: rsyslog
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: 0644
