---
- name: Get hostname
  shell: "raspi-config nonint get_hostname"
  register: pi_hostname
  changed_when: False

- name: Set hostname
  shell: "raspi-config nonint do_hostname {{ inventory_hostname }}"
  when: pi_hostname.stdout != inventory_hostname

- name: Check if FS is expandable
  shell: "raspi-config nonint get_can_expand"
  register: fs_filled
  changed_when: False

- name: Expand Filesystem
  shell: "raspi-config nonint do_expand_rootfs"
  when: fs_filled.stdout != '0'

- name: Set GPU memory split
  shell: raspi-config nonint do_memory_split 16

- name: Add rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: "0755"

- name: Add LED service
  copy:
    src: led.service
    dest: /lib/systemd/system/led.service
    owner: root
    group: root
    mode: "0644"

- name: Enable & start LED service
  service:
    name: led
    enabled: yes
    state: restarted

- name: Set master fact
  set_fact:
    k3s_role: "{{ (inventory_hostname == 'picluster-01' ) | ternary('master', 'worker') }}"

- name: Reboot for file system expansion
  reboot:
    reboot_timeout: 600
  when: fs_filled.stdout != '0'
