---
- name: Install and configure K3s
  hosts: picluster_leader:picluster_server:picluster_agent
  order: sorted
  remote_user: ansible
  roles:
    - iptables
    - k3s_configure
    - k3s_get_config
  become: true
