---
- name: Raspberry Pi First run
  hosts: linux:picluster_leader:picluster_server:pi.home.lan
  order: sorted
  remote_user: pi
  roles:
    - pi_firstrun

- name: Update packages
  hosts: linux:picluster_leader:picluster_server:pi.home.lan
  order: sorted
  remote_user: ansible
  roles:
    - packages
  become: true
