---
- hosts: linux:picluster_leader
  order: sorted
  remote_user: pi
  roles:
    - pi-firstrun

- hosts: linux:picluster_leader
  order: sorted
  remote_user: ansible
  roles:
    - packages
  become: yes
