---
- name: Upgrade packages with rescue
  block:
  - name: Update packages through apt
    apt:
      name: "*"
      state: latest
    become: yes
    when: ansible_os_family == "Debian"
  rescue:
  - name: Wait 10 seconds
    wait_for:
      timeout: 10
  - name: Update packages through apt (2nd attempt)
    apt:
      name: "*"
      state: latest
    become: yes
    when: ansible_os_family == "Debian"

- name: Install snmpd
  apt:
    name: snmpd
    state: latest
  become: yes
  when: ansible_os_family == "Debian"
- name: Download and enable Raspberry Pi SNMP Extend
  get_url:
    url:  https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/raspberry.sh 
    dest: /etc/snmp/raspberry.sh
    mode: 0700
  become: yes
- name: Ensure Debian-snmp user can execute file
  file:
    path: /etc/sudoers.d/011-snmp
    content: "Debian-snmp ALL=(ALL) NOPASSWD: /bin/sh /etc/snmp/raspberry.sh"
    mode: 0600
  become: yes
- name: Add snmpd.conf
  copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: "0600"
  become: yes
- name: Restart service
  service:
    name: snmpd
    state: restarted
  become: yes