---
- name: Upgrade packages with rescue
  block:
  - name: Update packages through apt
    apt:
      name: "*"
      state: latest
    when: ansible_os_family == "Debian"
  rescue:
  - name: Wait 10 seconds
    wait_for:
      timeout: 10
  - name: Update packages through apt (2nd attempt)
    apt:
      name: "*"
      state: latest
    when: ansible_os_family == "Debian"

- name: Install ntpdate
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Debian"
  with_items:
    - ntpdate
    - ntp

- name: Install iscsi
  apt:
    name: open-iscsi
    state: latest
  when: ansible_os_family == "Debian"

- name: Install snmpd
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Debian"
  with_items:
    - snmpd
    - snmp-mibs-downloader
- name: Download and enable Raspberry Pi SNMP Extend
  get_url:
    url:  https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/raspberry.sh 
    dest: /etc/snmp/raspberry.sh
    mode: 0700
- name: Ensure Debian-snmp user can execute file
  copy:
    dest: /etc/sudoers.d/011_snmp
    content: "Debian-snmp ALL=(ALL) NOPASSWD: /bin/sh /etc/snmp/raspberry.sh\n"
    mode: 0440
- name: Add snmpd.conf
  copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: "0600"
- name: Update service command line
  lineinfile:
    path: /lib/systemd/system/snmpd.service
    line: ExecStart=/usr/sbin/snmpd -LS6d -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux,mteTrigger,mteTriggerConf -f -p /run/snmpd.pid
    regexp: '^ExecStart'
- name: Reload daemon and restart service
  systemd:
    name: snmpd
    daemon_reload: yes
    state: restarted
