apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: 1password
  namespace: 1password
spec:
  repo: https://1password.github.io/connect-helm-charts
  chart: connect
  targetNamespace: 1password
  version: "1.17.0"
  valuesContent: |-
    commonLabels: {}
    connect:
      replicas: 1
      api:
        name: connect-api
        imageRepository: 1password/connect-api
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 0.2
        httpPort: 8080
        httpsPort: 8443
        logLevel: info
        serviceMonitor:
          enabled: true
          interval: 30s
          path: "/metrics"

      sync:
        name: connect-sync
        imageRepository: 1password/connect-sync
        resources: {}
        httpPort: 8081
        logLevel: info
      serviceType: NodePort

      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json

      imagePullPolicy: IfNotPresent

      # List of secret names to use as image pull secrets. Secrets must exist in the same namespace.
      imagePullSecrets:
        - dockerhub

      # The 1Password Connect version to pull
      version: "1.7.3"

      ## Horizontal Pod Autoscaling for the Connect pod
      hpa:
        # Enable Horizontal Pod Autoscaling for the Connect pod
        enabled: false
        # Additional annotations to be added to the HPA Connect
        annotations: {}
        # Minimum number of replicas for the Connect pod
        minReplicas: 1
        # Maximum number of replicas for the Connect pod
        maxReplicas: 3
        # Average Memory utilization percentage for the Connect pod
        avgMemoryUtilization: 50
        # Average CPU utilization percentage for the Connect pod
        avgCpuUtilization: 50
        # Defines the Autoscaling Behavior in up/down directions
        behavior: {}

      ## Pod Disruption Budget for the Connect pod
      pdb:
        # Enable Pod Disruption Budget for the Connect pod
        enabled: false
        # Additional annotations to be added to the PDB Connect
        annotations: {}
        # Number of pods that are unavailble after eviction as number or percentage (eg.: 50%)
        maxUnavailable: 1
        # Number of pods that are available after eviction as number or percentage (eg.: 50%)
        minAvailable: 0

      probes:
        liveness: true
        readiness: true

    operator:
      create: true
      replicas: 1

      # Denotes whether the 1Password Operator will automatically restart deployments based on associated updated secrets.
      autoRestart: true
      imagePullSecrets:
        - dockerhub
      imageRepository: 1password/onepassword-operator
      pollingInterval: 300
      version: "1.8.1"

      ## Horizontal Pod Autoscaling for the Operator pod
      hpa:
        # Enable Horizontal Pod Autoscaling for the Operator pod
        enabled: false
        # Additional annotations to be added to the HPA Operator
        annotations: {}
        # Minimum number of replicas for the Operator pod
        minReplicas: 1
        # Maximum number of replicas for the Operator pod
        maxReplicas: 3
        # Average Memory utilization percentage for the Operator pod
        avgMemoryUtilization: 50
        # Average CPU utilization percentage for the Operator pod
        avgCpuUtilization: 50
        # Defines the Autoscaling Behavior in up/down directions
        behavior: {}

      ## Pod Disruption Budget for the Operator pod
      pdb:
        # Enable Pod Disruption Budget for the Operator pod
        enabled: false
        # Additional annotations to be added to the PDB Operator
        annotations: {}
        # Number of pods that are unavailble after eviction as number or percentage (eg.: 50%)
        maxUnavailable: 1
        # Number of pods that are available after eviction as number or percentage (eg.: 50%)
        minAvailable: 0

      # A list of namespaces for the 1Password Operator to watch and manage. Use the empty list to watch all namespaces.
      watchNamespace: []

      # The resources requests/limits for the 1Password Operator pod
      resources: {}

      # 1Password Operator Token Configuration
      token:
        # The name of Kubernetes Secret containing the 1Password Connect API token
        name: onepassword-token
        # The key for the 1Password Connect token stored in the 1Password token secret
        key: token
      serviceAccount:
        create: true
      roleBinding:
        create: true
      clusterRole:
        create: true
      clusterRoleBinding:
        create: true

      # 1Password Operator Log Level Configuration
      logLevel: info
