---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io
  chart: cilium
  targetNamespace: kube-system
  version: "1.16.1"
  valuesContent: |-
    bpf:
      hostLegacyRouting: false
    cluster:
      name: default
    cni:
      customConf: false
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
      hostConfDirMountPath: /host/var/lib/rancher/k3s/agent/etc/cni/net.d
      binPath: /var/lib/rancher/k3s/data/current/bin
      uninstall: false
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
        - 10.43.0.0/16
    operator:
      replicas: 1
      resources:
        requests:
          cpu: 15m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 128Mi
      unmanagedPodWatcher:
        restart: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    policyEnforcementMode: default
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    routingMode: tunnel
    resources:
      requests:
        cpu: 75m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 512Mi
    serviceAccounts:
      cilium:
        name: cilium
      operator:
        name: cilium-operator
    tunnelPort: 8473
    tunnelProtocol: vxlan
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
    upgradeCompatibility: "1.15"
