apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  targetNamespace: nginx
  version: "4.11.2"
  valuesContent: |-
    controller:
      metrics:
        enabled: true
      extraArgs:
        default-ssl-certificate: nginx/star-home-lan-vault
    serviceAccount:
      name: ingress-nginx-controller
    tcp:
      "5432": postgresql-green/postgresql-green-primary:5432
