apiVersion: v1
kind: Namespace
metadata:
  name: argocd
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: 1password
spec:
  finalizers:
  - kubernetes