---
- name: Get Node Exporter versions
  ansible.builtin.uri:
    url: https://api.github.com/repos/prometheus/node_exporter/tags
    body_format: json
  register: nvsions
  run_once: true
  delegate_to: localhost
  become: false

- name: Set latest Node Exporter version
  ansible.builtin.set_fact:
    nv: "{{ nvsions.json[0].name }}"

- name: Check if Node Exporter is up-to-date
  ansible.builtin.shell: |
    set -o pipefail
    /usr/local/bin/node_exporter --version | grep $(echo "{{ nv }}" | tr -d v)
  args:
    executable: /bin/bash
  register: version_check_output
  failed_when: false
  changed_when: false

- name: Register if update is needed
  ansible.builtin.set_fact:
    needs_update: "{{ version_check_output.rc == 1 }}"

- name: Install/update Node Exporter
  when: needs_update
  block:
    - name: Set architecture to download
      ansible.builtin.set_fact:
        arch:
          armv7l: armv7
          aarch64: arm64
          i386: "386"

    - name: Download latest Node Exporter
      ansible.builtin.uri:
        url: |-
          https://github.com/prometheus/node_exporter/releases/download/{{ nv }}/node_exporter-{{ nv[1:] }}.linux-{{ arch[ansible_facts.architecture] }}.tar.gz
        return_content: true
      register: node_exporter

    - name: Add script to nodes
      ansible.builtin.copy:
        content: "{{ node_exporter.content }}"
        dest: "/tmp/node-exporter.tar.gz"
        owner: root
        group: root
        mode: "0644"

    - name: Ensure gzip / unzip are available
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - gzip
        - zip

    - name: Extract binary
      ansible.builtin.unarchive:
        src: /tmp/node-exporter.tar.gz
        include:
          - "node_exporter-{{ nv[1:] }}.linux-{{ arch[ansible_facts.architecture] }}/node_exporter"
        dest: /usr/local/bin
        remote_src: true
        extra_opts:
          - --strip-components
          - "1"
      notify:
        - Restart node exporter

    - name: Create/update service
      ansible.builtin.copy:
        src: files/node-exporter.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: '0400'
      notify:
        - Restart node exporter
