apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  version: "5.28.1"
  valuesContent: |-
    controller:
      logFormat: json
    server:
      logFormat: json
      extraArgs:
        - --insecure
      ingress:
        enabled: true
        hosts:
          - argocd.home.lan
        tls:
        - hosts:
          - argocd.home.lan
          secretName: argocd-ingress-secret
        annotations:
          cert-manager.io/cluster-issuer: vault-issuer
          cert-manager.io/common-name: argocd.home.lan
    repoServer:
      logFormat: json
