apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  version: "5.34.6"
  valuesContent: |-
    global:
      image:
        tag: v2.7.3
    configs:
      rbac:
        policy.csv: |-
          p, role:org-admin, applications, *, */*, allow
          p, role:org-admin, clusters, *, */*, allow
          p, role:org-admin, respositories, *, */*, allow
          p, role:org-admin, logs, *, */*, allow
          p, role:org-admin, exec, *, */*, allow
          g, ArgoCD Admins, role:org-admin
    server:
      url: https://argocd.home.lan
      extraArgs:
        - --insecure
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - argocd.home.lan
        tls:
        - hosts:
          - argocd.home.lan
          secretName: argocd-ingress-secret
        annotations:
          cert-manager.io/cluster-issuer: vault-issuer
          cert-manager.io/common-name: argocd.home.lan
      volumes:
        - hostPath:
            path: /etc/ssl/certs
          name: certs
      volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certs
          readOnly: true
    repoServer:
      logFormat: json
    dex:
      image:
      volumes:
        - hostPath:
            path: /etc/ssl/certs
          name: certs
      volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certs
          readOnly: true
    redis:
      image:
        tag: 7.0.11-alpine
