apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  version: "5.46.8"
  valuesContent: |-
    global:
      image:
        tag: v2.8.4
    configs:
      cm:
        create: true
        url: https://argocd.home.lan
        dex.config: |
          connectors:
          - config:
              issuer: https://authentik.home.lan/application/o/argocd/
              clientID: 658578a26fd391df56029e6d61c0d537a9358cb4
              clientSecret: $dex.authentik.clientSecret
              insecureEnableGroups: true
              scopes:
                - openid
                - profile
                - email
            name: authentik
            type: oidc
            id: authentik
        admin.enabled: "true"
        application.instanceLabelKey: argocd.argoproj.io/instance
        exec.enabled: "false"
        resource.compareoptions: |
          ignoreDifferencesOnResourceUpdates: true
        resource.customizations.ignoreResourceUpdates.argoproj.io_Application: |
          jsonPointers:
            - /status
            - /status/reconciledAt
            - /metadata/generation
            - /metadata/resourceVersion
        resource.ignoreResourceUpdatesEnabled: "true"
        server.rbac.log.enforce.enable: "false"
        timeout.hard.reconciliation: 0s
        timeout.reconciliation: 180s
      params:
        create: true
        controller.operation.processors: "10"
        controller.status.processors: "10"
      rbac:
        policy.csv: |-
          p, role:org-admin, applications, *, */*, allow
          p, role:org-admin, clusters, *, */*, allow
          p, role:org-admin, respositories, *, */*, allow
          p, role:org-admin, logs, *, */*, allow
          p, role:org-admin, exec, *, */*, allow
          g, project_admin, role:org-admin
          p, backstage, applications, get, */*, allow
    server:
      url: https://argocd.home.lan
      extraArgs:
        - --insecure
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - argocd.home.lan
        tls:
        - hosts:
          - argocd.home.lan
          secretName: argocd-ingress-secret
        annotations:
          cert-manager.io/cluster-issuer: vault-issuer
          cert-manager.io/common-name: argocd.home.lan
    repoServer:
      logFormat: json
    controller:
      resources:
        requests:
          cpu: 250m
          memory: 300Mi
        limits:
          cpu: 500m
          memory: 350Mi
    dex:
      image:
        tag: v2.37.0
      volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certs
          readOnly: true
      volumes:
        - hostPath:
            path: /etc/ssl/certs
          name: certs
    redis:
      image:
        tag: 7.0.13-alpine
    repositories:
      all:
        url: git@github.com:janikgar/home-k8s.git
        type: git
      semaphore:
        url: git@github.com:janikgar/semaphore-home-k8s.git
        type: git
    credentialTemplates:
      gitssh:
        url: git@github.com:janikgar/home-k8s.git
        sshPrivateKey: |
          REPLACE WITH APPROPRIATE KEY
      gitssh2:
        url: git@github.com:janikgar/semaphore-home-k8s.git
        sshPrivateKey: |
          REPLACE WITH APPROPRIATE KEY
    notifications:
      notifiers:
        service.webhook.consul-app-version: |
          url: https://consul.home.lan/v1/kv/
          service.alertmanager: |
            targets:
              - alertmanager-operated.prometheus.svc.cluster.local:9093
      templates:
        template.alertmanager-notification: |
          message: "Application {{.app.metadata.name}} has update. Status: {{.app.status.sync.status}}, Health: {{.app.status.health.status}}"
          alertmanager:
            generatorURL: "https://argocd.home.lan/applications/argocd/{{.app.metadata.name}}"
            labels:
              origin: argocd
              app: "{{.app.metadata.name}}"
              namespace: argocd
              destNamespace: "{{.app.spec.destination.namespace}}"
              status: "{{.app.status.sync.status}}"
              health: "{{.app.status.health.status}}"
              revision: "{{.app.status.sync.revision}}"
        template.app-version-notification: |
          webhook:
            consul-app-version:
              method: PUT
              path: /argocd-versions/{{.app.metadata.name}}
              body: |
                {"deployed_version": "{{.app.status.sync.revision}}"}
      triggers:
        trigger.on-is-deployed: |
          - when: app.status.sync.status == 'Synced' and app.status.health.status == 'Healthy'
            send: [app-version-notification, alertmanager-notification]
