apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io
  chart: cilium
  targetNamespace: kube-system
  version: "1.14.7"
  valuesContent: |-
    bpf:
      hostLegacyRouting: false
    cluster:
      name: default
    cni:
      customConf: false
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
      hostConfDirMountPath: /host/var/lib/rancher/k3s/agent/etc/cni/net.d
      binPath: /var/lib/rancher/k3s/data/current/bin
      uninstall: false
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
        - 10.43.0.0/16
    operator:
      replicas: 1
      unmanagedPodWatcher:
        restart: true
    policyEnforcementMode: never
    routingMode: tunnel
    serviceAccounts:
      cilium:
        name: cilium
      operator:
        name: cilium-operator
    tunnelPort: 8473
    tunnelProtocol: vxlan
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
