apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  targetNamespace: nginx
  version: "4.0.17"
  valuesContent: |-
    controller:
      podAnnotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: 80,443,8443,9090
        consul.hashicorp.com/transparent-proxy-exclude-outbound-cidrs: 10.43.0.1/32
      metrics:
        enabled: true
      extraArgs:
        default-ssl-certificate: default/star-home-lan
    serviceAccount:
      name: ingress-nginx-controller