---
- name: Check K3s roles
  debug:
    msg: "{{ ansible_host }}: {{ k3s_role }}"
    
- name: Worker node tasks
  when: k3s_role == 'agent'
  block:
    - name: Gracefully stop worker
      shell: /usr/local/bin/k3s-killall.sh
    - name: Uninstall K3s from worker
      shell: /usr/local/bin/k3s-agent-uninstall.sh

- name: Server node tasks
  when: k3s_role != 'agent'
  block:
    - name: Gracefully stop server
      shell: /usr/local/bin/k3s-killall.sh
    - name: Uninstall K3s from server
      shell: /usr/local/bin/k3s-uninstall.sh