---
- name: Raspi Config setup
  ansible.builtin.import_tasks: raspi-config.yml

- name: Replace rsyslog logrotate Config
  ansible.builtin.copy:
    src: rsyslog
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: '0644'

- name: Back Up old MOTD
  ansible.builtin.command: cp /etc/motd /etc/motd.old
  changed_when: true

- name: Add new MOTD
  ansible.builtin.copy:
    src: files/motd
    dest: /etc/motd
    owner: root
    mode: "0644"

- name: Install zram-tools
  ansible.builtin.apt:
    package:
      - zram-tools
    state: present

- name: Include zram module
  community.general.system.modprobe:
    name: zram
    state: present

- name: If zram is not present
  when: not "zram0" in ansible_facts['devices'].keys()
  block:
    - name: Configure zram swap
      ansible.builtin.copy:
        dest: /etc/default/zramswap
        mode: '0644'
        content: |-
          ALGO=lz4
          PERCENT=50

    - name: Start zramswap service
      ansible.builtin.systemd:
        service: zramswap
        state: started
        enabled: true
