---
- name: Raspi Config setup
  ansible.builtin.import_tasks: raspi-config.yml

- name: Replace rsyslog logrotate Config
  ansible.builtin.copy:
    src: rsyslog
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: '0644'

- name: Back Up old MOTD
  ansible.builtin.command: cp /etc/motd /etc/motd.old
  changed_when: true

- name: Add new MOTD
  ansible.builtin.copy:
    src: files/motd
    dest: /etc/motd
    owner: root
    mode: "0644"
