---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Add rc.local
  ansible.builtin.copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: "0755"

- name: Add LED service
  ansible.builtin.copy:
    src: led.service
    dest: /lib/systemd/system/led.service
    owner: root
    group: root
    mode: "0644"

- name: Enable & start LED service
  ansible.builtin.service:
    name: led
    enabled: true
    state: restarted

- name: Set server fact
  ansible.builtin.set_fact:
    k3s_role: "{{ k3s_role }}"
