---
- name: Get hostname
  ansible.builtin.command: "raspi-config nonint get_hostname"
  register: pi_hostname
  changed_when: false

- name: Set hostname
  ansible.builtin.command: "raspi-config nonint do_hostname {{ inventory_hostname }}"
  when: pi_hostname.stdout != inventory_hostname
  changed_when: true

- name: Check if FS is expandable
  ansible.builtin.command: "raspi-config nonint get_can_expand"
  register: fs_filled
  changed_when: false

- name: Expand Filesystem
  ansible.builtin.command: "raspi-config nonint do_expand_rootfs"
  when: fs_filled.stdout != '0'
  changed_when: true

- name: Set GPU memory split
  ansible.builtin.command: raspi-config nonint do_memory_split 16
  changed_when: true

- name: Add rc.local
  ansible.builtin.copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: "0755"

- name: Add LED service
  ansible.builtin.copy:
    src: led.service
    dest: /lib/systemd/system/led.service
    owner: root
    group: root
    mode: "0644"

- name: Enable & start LED service
  ansible.builtin.service:
    name: led
    enabled: true
    state: restarted

- name: Set server fact
  ansible.builtin.set_fact:
    k3s_role: "{{ k3s_role }}"

- name: Reboot for file system expansion
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: fs_filled.stdout != '0'
