---
- name: Get hostname
  shell: "raspi-config nonint get_hostname"
  register: pi_hostname
  changed_when: False

- name: Set hostname
  shell: "raspi-config nonint do_hostname {{ inventory_hostname }}"
  when: pi_hostname.stdout != inventory_hostname

- name: Add config.txt
  copy:
    src: config.txt
    dest: /boot/config.txt
    owner: root
    group: root
    mode: "0400"

- name: Modify cmdline.txt
  shell: |-
    set -euo pipefail
    echo $(cat /boot/cmdline.txt) cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory > /tmp/cmdline.txt
    cat /tmp/cmdline.txt > /boot/cmdline.txt
    rm /tmp/cmdline.txt

- name: Add rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: "0755"

- name: Add LED service
  copy:
    src: led.service
    dest: /lib/systemd/system/led.service
    owner: root
    group: root
    mode: "0644"

- name: Enable & start LED service
  service:
    name: led
    enabled: yes
    state: restarted

- name: Try to expand FS
  block:
  - name: Check if FS is expandable
    shell: "raspi-config nonint get_can_expand"
    register: fs_filled
    changed_when: False

  - name: Expand Filesystem
    shell: "raspi-config nonint do_expand_rootfs"
    when: fs_filled.stdout != '0'

  - name: Set GPU memory split
    shell: raspi-config nonint do_memory_split 16

  - name: Reboot for file system expansion
    reboot:
      reboot_timeout: 600
    when: fs_filled.stdout != '0'
  rescue:
    - name: Skip
      debug:
        msg: "Unable to expand FS"
