---
- name: Download CA Cert
  ansible.builtin.uri:
    url: http://certs.home.lan/ca.crt
    return_content: true
  register: ca_cert
  delegate_to: localhost
  become: false
  run_once: true
  retries: 10
  delay: 5
  until: ca_cert is not failed

- name: Download Int Cert
  ansible.builtin.uri:
    url: http://certs.home.lan/int.crt
    return_content: true
  register: int_cert
  delegate_to: localhost
  become: false
  run_once: true
  retries: 10
  delay: 5
  until: int_cert is not failed

- name: Add CA cert to nodes
  ansible.builtin.copy:
    content: "{{ ca_cert.content }}"
    dest: "/usr/local/share/ca-certificates/ca_home_lan.crt"
    owner: root
    group: root
    mode: "0400"

- name: Add Int cert to nodes
  ansible.builtin.copy:
    content: "{{ int_cert.content }}"
    dest: "/usr/local/share/ca-certificates/star_home_lan.crt"
    owner: root
    group: root
    mode: "0400"

- name: Update CA certs
  ansible.builtin.command: update-ca-certificates
  register: update_cert
  changed_when: ( update_cert.stdout | regex_findall('(\\d+) (?:added|removed)') | map('int') | sum ) != 0
  notify:
    - Reload k3s systemd service
    - Reload k3s-agent systemd service

- name: DEBUG
  ansible.builtin.debug:
    msg: "{{ update_cert.stdout | regex_findall('(\\d+) (?:added|removed)') | map('int') | sum }}"
