- name: Set password to non-default
  user:
    name: pi
    update_password: always
    password: $6$wpHezfpR7vZr.eMf$zBL6CJKQ5ITU0aFLlagJziogrXEbvdz5zNCKV9y7ul9z4oCrSy/VbFH6FUGP4ziQLMquHfQSJuZL2u1uy4HdC0
  become: yes

- name: Create SSH directory
  file:
    dest: /home/pi/.ssh/
    state: directory
    owner: pi
    group: pi

- name: Add SSH key to authorized_keys
  copy:
    content: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCq0qnsZESMxrijyNKeBLHhfNJDf+ewxwlnq0kW9EG3LGU5qytNyFvpxKO94fDfqmCKF9zVMZBpYL8iRs3BFPDWFD4mC6Dnw3DQD3S+RTTRTLopanb8b76e2BQe9BB2HYtriHi9M9oL9HjX56VgOiXigkgI7B06nDNd0PgZ0tLaHQxQwIkW1J4QDh8HNYyO+ugfTw13+FKxw6C7o/sXoSYdYxm5fu4er2M4RItsk6rIo2rxrB98O2VCcjwpk26rCNvNr0iPtQUnNZyaO9kRd0aMMLx1MPb4gI/gdmlUcaUXu1EIB+LJe+tW2t7m3IRCxHWbnKiYxi2n02AhgJpd/eDFaV6DjCAWnJH4mM73BtkaHA53LigR5buiguTc1mYIetwyJptA3o5ykI2frMDS1gQghe4EZbnGw8dsAOwVdZkn24AP7IzUOgz1DZcXktcfzrI4BpzWnwPjguqCXFgKAzeZLtYewek2J5yAX203UWi+jExqt2lOEduYVp9dXuxntB6fXvP61qk9Qt4mu4Ksh9gPZRAeudNHcSn9AKO/EUYg+qwae7DgM9MfUaeFEDTZTS7Eh62lBY+jsTOpO6mBCU1LElWn2qfz6mP/IrBMZPylDpeZaDU7UEHId/oy42MGfm3rjTtd4AE7wbg3nqy74boDn8T4kgtLeyAxhTpqKKWOVQ==
    dest: /home/pi/.ssh/authorized_keys
    owner: pi
    group: pi
    mode: "0444"
